name: Makefile CI

on:
  push:
    branches: [ "owrt23.05" ]
  pull_request:
    branches: [ "owrt23.05" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache OpenWRT build

      uses: actions/cache@v4

      with:

        path: |

          .config

          bin/

          feeds/

        key: ${{ runner.os }}-openwrt-${{ hashFiles('**/feeds.conf.default') }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip bison flex ccache

    - name: Set up ccache

      run: |

        export CC="ccache gcc"

        export CXX="ccache g++"
      
    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build OpenWRT
      run: |
         make defconfig
         make -j$(nproc) download world 
